name: entailment-tda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.10
  - aiosignal=1.3.2
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - datasets=3.6.0
  - deprecated=1.2.18
  - dill=0.3.8
  - expat=2.7.1
  - filelock=3.17.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2025.3.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - hopcroftkarp=1.2.4
  - huggingface_hub=0.31.2
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=20.1.6
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=20.1.6
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - narwhals=1.41.1
  - ncurses=6.4
  - networkx=3.3
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=3.5.0
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.2.3
  - patsy=1.0.1
  - persim=0.3.8
  - pillow=11.1.0
  - pip=25.1
  - plotly=6.1.2
  - propcache=0.3.1
  - pyarrow=19.0.0
  - pybind11-abi=4
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - ripser=0.6.12
  - safetensors=0.5.3
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - transformers=4.52.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - umap-learn=0.5.3
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - asttokens==3.0.0
      - comm==0.2.2
      - cython==3.1.2
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - geoopt==0.5.0
      - giotto-ph==0.2.4
      - giotto-tda==0.6.2
      - igraph==0.11.8
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jupyterlab-widgets==3.0.15
      - kmapper==2.1.0
      - matplotlib-inline==0.1.7
      - parso==0.8.4
      - pexpect==4.9.0
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyflagser==0.4.7
      - pygments==2.19.1
      - scikit-learn==1.3.2
      - scikit-tda==1.1.1
      - stack-data==0.6.3
      - tadasets==0.2.1
      - texttable==1.7.0
      - traitlets==5.14.3
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
